from . import name_sequence_mixin
from . import approval_config
from . import approval_record
from . import approval_log
from . import res_users
from . import approval_escalation
from . import mail_activity
from . import approval_settings
from . import approval_settings_state
from . import approval_forward
from . import res_config_settings
from . import cancellation_record
from . import state_tags
from . import ir_http
from . import approval_buttons
from . import approval_automation
from . import mail_template
from . import ir_model
from . import approval_log_voting
