from . import base
from . import ir_sequence
from . import ir_actions_actions
from . import tools
from . import ir_qweb
from . import res_config_settings
from . import xml_mixin
from . import ir_attachment
from . import many2many_attachment_res_id_mixin